### ISSUE TITLE
Some dude stole this

### ISSUE THREAD

**Issue by wxnnvs** [Hypverr/Solar-Client#2]
This random 9year old just deadass forked this repo and changed name to kittenclient 💀
https://github.com/CodingKitten-YT/KittenClient
Look at commits

**Comment by AODGGLEADER** [comment]
:skull:

**Comment by Hypverr** [comment]
Aint no way bro. I don't really care anyways, they can do whatever they want unless they claim that they made it.

**Comment by wxnnvs** [comment]
🗿
